#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/learn?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    initial-size: 15
    min-idle: 8
    max-active: 30
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 60
    validation-query: SELECT 1 FROM DUAL
    stat-view-servlet:
      enabled: true
    url: jdbc:mysql://localhost:3306/learn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    # call-setters-on-nulls 参数的作用是查询的某一行某一列为null，是否返回
#    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl